const RESPONSE_MESSAGE = {
    BLOCK_ACCOUNT: "Account has been blocked for next 5 minutes",
    ACCOUNT_NOT_VERIFIED: "Account is not verified", 
    EMAIL_ALREADY_EXISTS: "Email already exists",
    EMAIL_DOESNT_EXIST: "Email doesn't exists",
    FAILED_TO_SIGNUP: "Failed to signup",
    SIGNUP_SUCCESSFUL: "Successfully signup",
    FAILED_TO_LOGIN: "Failed to Login",
    LOGIN_SUCCESSFUL: "Successfully login",
    INVALID_CREDENTIAL: "Invalid Credential",
    INVALID_AUTHOR: "Failed to add author",
    FAILED_TO_GET_AUTHORS: "Failed to get authors data",
    FAILED_TO_GET_SINGLE_AUTHORS: "Failed to get author data",
    FAILED_TO_ADD_AUTHOR: "Invalid author",
    AUTHOR_NAME_EXISTS: "Author already exists",
    AUTHOR_ADDED: "Author added successfully",
    FAILED_TO_GET_USERS: "Failed to get users data",
    FAILED_TO_GET_SINGLE_USER: "Failed to get user data",
    USER_NOT_FOUND: "User not found",
    FAILED_TO_UPDATE_USER: "Failed to update user",
    GET_ALL_USERS: "Successfully get all users data",
    GET_USER: "Successfully get all user data",
    FAILED_TO_DELETE_USER: "Failed to delete user",
    DELETE_USER: "Successfully deleted user",
    USER_UPDATED: "Successfully updated user",
    PHONE_NUMBER_NOT_UNIQUE: "Phone number is not unique",
    GET_ALL_AUTHORS: "Successfully get all authors data",
    GET_AUTHOR: "Successfully get author data",
    FAILED_TO_GET_BOOKS: "Failed to get books data",
    FAILED_TO_GET_SINGLE_BOOK: "Failed to get book data",
    FAILED_TO_ADD_BOOK: "Failed to add book",
    FAILED_TO_UPDATE_BOOK: "Failed to update book",
    BOOK_ADDED: "Book added successfully",
    BOOK_UPDATED: "Book updated successfully",
    BOOK_EXISTS: "Book already exists",
    BOOK_DONT_EXISTS: "Book don't exists",
    GET_ALL_BOOKS: "Successfully get all books data",
    GET_BOOK: "Successfully get book data",
    FAILED_TO_DELETE_BOOK: "Failed to delete book",
    BOOK_DELETED: "Successfully deleted book"
};

module.exports = RESPONSE_MESSAGE;